spring.application.name=Backend

#Config datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/qivora?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Key API Google GenAI
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}

# Cau hinh model GenAI
spring.ai.google.genai.chat.model=gemini-2.5-flash

# Config jwt
jwt-secret=${JWT_SECRET}
jwt-expired=600000
jwt-refresh-secret=${JWT_REFRESH_SECRET}
jwt-refresh-expired=15552000000
jwt-reset-secret=${JWT_RESET_SECRET}

# Config Cloudinary
cloudinary.cloud-name=dll6mpwhk
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Config Multipart Upload
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
